server:
  port: 80
  servlet:
    context-path: /

---
file:
  path: d:/spring/file

spring:
  datasource:
    username: root
    password: Cc@123456
    url: jdbc:mysql://49.235.106.235:3306/tcs?useUnicode=true&amp;characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      exclude: static/**



---

mybatis:
  #config-location: classpath:mybatis.xml
  mapper-locations: classpath:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.bean

---

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

#通过configurationProperties的prefix
file:
  component:
    parentPath: e:/spring
    file-type: .java
    max-size: 18
demo:
  db:
    driver-class-name:
    url:
    username:
    password:

#userComponent
cs:
  user:
    username: wx
    age: 22
    married: true
    map: {key1: value1,key2: value2}
